language: objective-c
osx_image: xcode11
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/unit.sh
- chmod a+x ./Scripts/integration.sh
install:
- ./Scripts/install.sh
jobs:
  include:
    - stage: unit
      script: ./Scripts/unit.sh
    - stage: integration
      script: ./Scripts/integration.sh
    - stage: build
      script: ./Scripts/build.sh

